// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20241012082137_ProductConfigurations")]
    partial class ProductConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accesories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product for children"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Home goods"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ImagePath = "https://static1.squarespace.com/static/5c56a66665019fdb54fb83be/t/637f1fd84aea254bc9a93a25/1669275613716/GOOGLE_PIXEL_7PRO_MAIN.jpg?format=1500w",
                            Name = "Google Pixel 7 Pro",
                            Price = 7800m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ImagePath = "https://cdn.new-brz.net/app/public/models/MQ183SX-A/large/w/221108190028339335.webp",
                            Name = "IPhone 14 Pro",
                            Price = 35000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ImagePath = "https://world-smartphones.com.ua/image/data/phones/Motorola/Moto-G8-Power/motorola-moto-g8-power-prev.jpg",
                            Name = "Motorola G8",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ImagePath = "https://stark.kiev.ua/wa-data/public/shop/products/24/24/2424/images/1080/1080.970.jpg",
                            Name = "Power Bank",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            ImagePath = "https://belker.com.ua/content/images/14/536x536l50nn0/besprovodnye-naushniki-xiaomi-redmi-airdots-black-zbw4480gl-16031737044081.jpg",
                            Name = "Air dots",
                            Price = 999m
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Product", b =>
                {
                    b.HasOne("DataAccess.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
